name: Generate Contributors

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Generate contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          readme_path: "CONTRIBUTORS.md"
          commit_message: "docs: update contributors list"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
